export const iceMapFishingPlaces = [
  {
    id: 1,
    title: 'Whitefish Lake, Montana (USA)',
    coords: '48.4100° N, 114.3400° W',
    image: require('../../assets/images/icemapplace1.png'),
    text: `This lake has a quietness in winter that you rarely find in popular places. The ice here is strong, and on clear days you can see the distant ridges of the Rocky Mountains. Fishermen come for trout and light-colored sedge beauty - the water is clean, and the air smells of tar and frost. The lake is convenient in that there is a small town nearby, but nature still feels wild, real and peaceful.`,
  },
  {
    id: 2,
    title: 'Inari Lake, Finland',
    coords: '68.9050° N, 27.9500° E',
    image: require('../../assets/images/icemapplace2.png'),
    text: `One of the largest and cleanest lakes in Lapland. Transparent thick ice, pine forests in snow, morning mists. Locals say silence has its own sound here.`,
  },
  {
    id: 3,
    title: 'Lake Saimaa, Finland',
    coords: '61.3184° N, 28.0835° E',
    image: require('../../assets/images/icemapplace3.png'),
    text: `Saimaa is a labyrinth of islands and frozen bays. The lake glows under the sun and often shows northern lights at night.`,
  },
  {
    id: 4,
    title: 'Great Slave Lake, Canada',
    coords: '61.8608° N, 114.4786° W',
    image: require('../../assets/images/icemapplace4.png'),
    text: `One of the best winter places in Canada. Deep, clean, with stable ice and huge lake trout.`,
  },
  {
    id: 5,
    title: 'Lago Fagnano, Argentina (Patagonia)',
    coords: '54.6664° S, 67.2928° W',
    image: require('../../assets/images/icemapplace5.png'),
    text: `Patagonia energy combined with stillness. Ice appears only in zones, but the views and wildlife are unforgettable.`,
  },
  {
    id: 6,
    title: 'Storvatnet Lake, Norway',
    coords: '70.2371° N, 19.3451° E',
    image: require('../../assets/images/icemapplace6.png'),
    text: `Cold, mountains, long-lasting clear ice. True northern spirit.`,
  },
  {
    id: 7,
    title: 'Goose Lake, Michigan (USA)',
    coords: '44.2609° N, 34.0335° W',
    image: require('../../assets/images/icemapplace7.png'),
    text: `Small, cozy, quiet, reliable ice. Locals love it for stability.`,
  },
  {
    id: 8,
    title: 'Bitter Lake, South Dakota (USA)',
    coords: '45.3608° N, 37.4979° W',
    image: require('../../assets/images/icemapplace8.png'),
    text: `Interesting ice formations, excellent perch and pike, very quiet remote spots.`,
  },
  {
    id: 9,
    title: 'Ivotsty Lake, Russia',
    coords: '67.6524° N, 33.0473° E',
    image: require('../../assets/images/icemapplace9.png'),
    text: `Very peaceful lake surrounded by pine trees and soft hills. Ice lasts all season.`,
  },
  {
    id: 10,
    title: 'Mingan Archipelago, Canada',
    coords: '50.1408° N, 64.3604° W',
    image: require('../../assets/images/icemapplace10.png'),
    text: `Rocky shores, frozen bays, sea ice patterns, and seabirds even in winter.`,
  },
  {
    id: 11,
    title: 'Kirkjubæjarklaustur, Iceland',
    coords: '63.7832° N, 18.5416° W',
    image: require('../../assets/images/icemapplace11.png'),
    text: `Black volcanic rock + white snow = surreal landscapes, stable ice.`,
  },
  {
    id: 12,
    title: 'Skjærvatnet Lake, Norway',
    coords: '69.5209° N, 18.8189° E',
    image: require('../../assets/images/icemapplace12.png'),
    text: `Quiet lake not blown by wind, crystal air, strong ice.`,
  },
  {
    id: 13,
    title: 'Whitehorse Creek, Canada',
    coords: '53.3166° N, 118.7760° W',
    image: require('../../assets/images/icemapplace13.png'),
    text: `Frozen stream surrounded by spruce forests and blue shadows. Very cinematic spot.`,
  },
];
