export const iceMapFishingPlaces = [
  {
    id: 1,
    title: 'Whitefish Lake, Montana (USA)',
    coords: '48.4100° N, 114.3400° W',
    image: require('../../assets/images/icemapplace1.png'),
    text: `This lake has a quietness in winter that you rarely find in popular places. The ice here is strong, and on clear days you can see the distant ridges of the Rocky Mountains. Fishermen come for trout and light-colored sedge beauty - the water is clean, and the air smells of tar and frost. The lake is convenient in that there is a small town nearby, but nature still feels wild, real and peaceful.`,
  },
  {
    id: 2,
    title: 'Inari Lake, Finland',
    coords: '68.9050° N, 27.9500° E',
    image: require('../../assets/images/icemapplace2.png'),
    text: `One of the largest and cleanest lakes in Lapland. In winter, it is covered with thick transparent ice, and around it are pine trees covered in loose snow. Here you can catch smelt and halibut, but the real magic is in the mists that hang over the ice in the morning. Locals say that Inari is a place where silence sounds. The landscapes change depending on the weather: from bright blue to pearly white.`,
  },
  {
    id: 3,
    title: 'Lake Saimaa, Finland',
    coords: '61.3184° N, 28.0835° E',
    image: require('../../assets/images/icemapplace3.png'),
    text: `Saimaa is a labyrinth of islands, narrow straits and frozen bays. In winter, the lake looks especially fabulous: the ice is smooth, the snow-covered shores glow in the morning sun. Here you can often catch pike perch, and also watch the northern lights over the night sky. Even on cold days, the lake remains accessible, as there are several small parking lots and shelters for fishermen nearby.`,
  },
  {
    id: 4,
    title: 'Great Slave Lake, Canada',
    coords: '61.8608° N, 114.4786° W',
    image: require('../../assets/images/icemapplace4.png'),
    text: `
A huge northern lake with a depth of over 600 meters is one of the best places in Canada. The ice here is thick and reliable, and the horizons seem endless. Anglers choose Great Slave for its cleanliness, accessibility and the chance to catch large lake trout. In winter, the air is very transparent: it seems as if you can see for tens of kilometers.`,
  },
  {
    id: 5,
    title: 'Lago Fagnano, Argentina (Patagonia)',
    coords: '54.6664° S, 67.2928° W',
    image: require('../../assets/images/icemapplace5.png'),
    text: `Patagonia in winter is a wild energy of nature, but Lake Fagnano surprises with its tranquility. Ice covers only certain areas, so you need to fish carefully. But the reward is great: fresh air, mountain views and the opportunity to see a fox or guanaco on the shore. The lake stretches for tens of kilometers, and its scale is felt immediately.`,
  },
  {
    id: 6,
    title: 'Storvatnet Lake, Norway',
    coords: '70.2371° N, 19.3451° E',
    image: require('../../assets/images/icemapplace6.png'),
    text: `A harsh northern lake with beautiful mountain slopes. Ice forms here in December and lasts for a long time, and the clear air opens up gorgeous panoramas. Storvatnet is chosen by fishermen who are looking for silence and a true Nordic spirit. The fish bite steadily, but the local cold is felt sharply - you need to dress well.`,
  },
  {
    id: 7,
    title: 'Goose Lake, Michigan (USA)',
    coords: '44.2609° N, 34.0335° W',
    image: require('../../assets/images/icemapplace7.png'),
    text: `
A small, cozy lake hidden among coniferous forests. Locals often fish here, because the ice forms evenly and reliably. The atmosphere is very homely: low trees, soft snow and a complete absence of noisy tourists. Goose Lake is chosen by those who want simplicity and a stable bite.`,
  },
  {
    id: 8,
    title: 'Bitter Lake, South Dakota (USA)',
    coords: '45.3608° N, 37.4979° W',
    image: require('../../assets/images/icemapplace8.png'),
    text: `The lake is known for its uneven bottom and interesting ice formations. Under the thick layer of ice is an excellent population of perch and pike. In winter, it is easy to find remote, completely quiet spots here, where other fishermen rarely go. The weather changes quickly, so the place is ideal for those who love variety.`,
  },
  {
    id: 9,
    title: 'Ivotsty Lake, Russia',
    coords: '67.6524° N, 33.0473° E',
    image: require('../../assets/images/icemapplace9.png'),
    text: `A remote and picturesque lake among low trees and hills. Tourists hardly come here, so you fish in real silence. Medicinal pines, shining snow and pure frost make the atmosphere especially cozy. The ice lasts long and is even, allowing fishing almost all season long.`,
  },
  {
    id: 10,
    title: 'Mingan Archipelago, Canada',
    coords: '50.1408° N, 64.3604° W',
    image: require('../../assets/images/icemapplace10.png'),
    text: `This archipelago is known for its rocky shores and clear water. In winter, many bays freeze over, creating perfect “pockets” for fishing. The cold sea nearby forms interesting ice patterns. Seabirds can often be seen here even on frosty days — a unique atmosphere.`,
  },
  {
    id: 11,
    title: 'Kirkjubæjarklaustur, Iceland',
    coords: '63.7832° N, 18.5416° W',
    image: require('../../assets/images/icemapplace11.png'),
    text: `Icelandic winters are harsh, but the ice in this region forms evenly and predictably. The terrain is volcanic: black rocks contrast with white snow, creating surreal landscapes. The lakes and bays around the village are often suitable for winter fishing. The atmosphere is very cinematic and almost unreal.`,
  },
  {
    id: 12,
    title: 'Skjærvatnet Lake, Norway',
    coords: '69.5209° N, 18.8189° E',
    image: require('../../assets/images/icemapplace12.png'),
    text: `This is a quiet, intimate lake hidden among small mountains. The ice is strong, and the surrounding nature shines in the morning thanks to the crystal air. It is convenient to fish here even in unusual weather conditions - the lake is almost not blown by the wind.`,
  },
  {
    id: 13,
    title: 'Whitehorse Creek, Canada',
    coords: '53.3166° N, 118.7760° W',
    image: require('../../assets/images/icemapplace13.png'),
    text: `Although it is not a large lake, but a wide frozen stream, the place is popular with adventure lovers. The ice forms thick and smooth, and the shores are picturesque - tall spruce trees, blue shadows and fog over snow-covered rocks. The atmosphere is more like a scene from a movie than reality.`,
  },
];
