export const iceMapFishingTips = [
  'Check the ice thickness before each step.',
  'Ice from 10 cm is the minimum for one fisherman.',
  'Avoid dark and wet areas of ice.',
  'Take a rope 10–15 meters with you.',
  'Move slowly and without sudden jumps.',
  'Keep an ice pick ready — check every few meters.',
  'Wear several layers so as not to overheat and freeze.',
  'Have a supply of dry clothes in your backpack.',
  'Don’t fish alone — safety is in the company.',
  'Avoid river currents under the ice.',
  'Bays freeze faster — check their condition carefully.',
  'Drinking hot tea improves concentration.',
  'Wind reduces ice strength — avoid open places.',
  'Always let someone know where you are.',
  'Carry a flashlight even during the day.',
  'Cloudy weather = thinner ice — be careful.',
  'Take a heat-resistant container for bait.',
  'Check your tackle — cold spoils mechanics fast.',
  'Use bright baits in dark depths.',
  'Sit with your back to the wind to save heat.',
  'Make several holes — switch between them.',
  'Avoid crowds of fishermen — weight matters.',
  'Change depth if there is no bite.',
  'Keep hands warm — reaction depends on it.',
  "Don't put heavy equipment in one spot.",
  'Choose ice without cracks.',
  'At dawn fish are more active — don’t miss it.',
  'Listen to the ice — the crunch is a signal.',
  'Use lures with luminous elements at dusk.',
  'Use an insulated cover for spinners.',
  'Move along the shore, not across the lake.',
  'Fresh air increases fatigue — take breaks.',
  'Winter sun glare requires glasses.',
  'Check weather forecast before leaving.',
  'Make sure the ice is not covered with water.',
  'Fish react to pressure — consider changes.',
  'Move lures slowly — cold water slows fish.',
  'Experiment with lowering speed.',
  'Keep hooks sharp — extremely important.',
  "Don't drill holes too close together.",
  'Shadows on ice scare fish — change positions.',
  'Treat ice with respect — no overconfidence.',
  'Stimulate fish with light lure movements.',
  'Silence works better than noise.',
  'Don’t leave things on the ice — wind takes them.',
  'Keep feet warm — they freeze first.',
  "If ice sings — don't panic, but stay aware.",
  'Pick spots protected by trees.',
  'Fresh air is good, but don’t sit too long.',
  'Finish fishing before dark — safety first.',
];
